pool_specification:
  id: docker-openfoam-rdma
  vm_configuration:
    platform_image:
      publisher: OpenLogic
      offer: CentOS-HPC
      sku: '7.4'
  vm_count:
    dedicated: 0
    low_priority: 0
  autoscale:
    evaluation_interval: 00:05:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 0
        low_priority: 2
  vm_size: STANDARD_H16R
  inter_node_communication_enabled: true
  per_job_auto_scratch: true
  ssh:
    username: shipyard
  virtual_network: 
    name: nfs-vnet
    resource_group: remotefs-rg
    create_nonexistant: true
    address_space: 10.0.0.0/16
    subnet:
      name: batch-vm-subnet
      address_prefix: 10.0.0.0/18


